blank_issues_enabled: false
contact_links:
  - name: ğŸ› SauceCTL Bug report
    url: https://github.com/saucelabs/saucectl/issues/new?template=1-bug-report.md
    about: Create a report to help us improve
  - name: ğŸš€ Feature Proposal
    url: https://github.com/saucelabs/saucectl/issues/new?template=feature.md
    about: Submit a proposal for a new feature
  - name: ğŸ¤” Questions and Help
    url: https://docs.saucelabs.com/web-apps/automated-testing/cypress/
    about: Visit our documentation to review frequently asked questions and use cases
  - name: ğŸ“ƒ Cypress Example Issue
    url: https://github.com/saucelabs/saucectl-cypress-example/issues/new
    about: Report any inaccurate or missing content
