apiVersion: v1
kind: cypress
defaults:
  mode: sauce
sauce:
  region: us-west-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - other tag
    build: Github Run $GITHUB_RUN_ID
docker:
  # Affects how test files are transferred to the docker container when using the docker mode.
  fileTransfer: copy # Choose between mount|copy.
cypress:
  version: 9.7.0 # See https://docs.saucelabs.com/testrunner-toolkit for a list of supported versions.
  configFile: "cypress.config.js"  # We determine related files based on the location of the config file.

# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites:
  - name: "Chrome in sauce"
    mode: sauce
    browser: "chrome"
    shard: spec
    platformName: "Windows 10"
    config:
      testingType: e2e
      specPattern: [ "cypress/e2e/**/*.*" ]
      env:
        allure: true
        allureResultsPath: __assets__/allure-results/

# Controls what artifacts to fetch when the suite on Sauce Cloud has finished.
artifacts:
  download:
    when: always
    match:
      - "*"
    directory: ./artifacts/
