name: saucectl cypress tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Saucectl RUN Docker and Cloud
        uses: saucelabs/saucectl-run-action@v1
        with:
          testing-environment: ""
          concurrency: 10
  cucumber:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          testing-environment: ""
          concurrency: 10

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: examples/cucumber/package-lock.json

      - name: Cypress with Cucumber
        working-directory: examples/cucumber
        run: |
          npm ci
          saucectl run
  typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          testing-environment: ""
          concurrency: 10

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: examples/typescript/package-lock.json

      - name: Cypress with Typescript
        working-directory: examples/typescript
        run: |
          npm ci
          saucectl run

  allure-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install saucectl
        uses: saucelabs/saucectl-run-action@v1
        with:
          skip-run: true
          testing-environment: ""
          concurrency: 10

      - name: Cypress with Allure Plugin
        run: |
          cd examples/allure-plugin
          saucectl run

