apiVersion: v1alpha
kind: cypress
sauce:
  region: us-west-1
  concurrency: 2 # Controls how many suites are executed at the same time.
  metadata:
    name: saucectl cypress example
    tags:
      - e2e
      - release team
      - other tag
    build: Release $CI_COMMIT_SHORT_SHA
docker:
  # Affects how test files are transferred to the docker container when using the docker mode (--test-env docker).
  fileTransfer: copy # Choose between mount|copy.
cypress:
  version: 5.6.0 # See https://docs.saucelabs.com/testrunner-toolkit for a list of supported versions.
  configFile: "cypress.json"  # We determine related files based on the location of the config file.
suites:
  - name: "Chrome"
    browser: "chrome"
    platformName: "Windows 10" # Only relevant when running a test against the sauce cloud (--test-env sauce).
    config:
      testFiles: [ "**/*.*" ] # Cypress native glob support.
  - name: "Firefox"
    browser: "firefox"
    platformName: "Windows 10"
    config:
      testFiles: [ "**/*.*" ]